#!/usr/bin/env python
"""
Plot the derivative of sigmoid using matplotlib

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""
import numpy as np
from project.plothelper import PlotHelper


def plot():
    """Plot the function"""
    def sigmoid(x):
        return 1 / (1 + np.e ** (-x))
    dsigmoid_dx = lambda x: sigmoid(x)*(1 - sigmoid(x)) # define f(x)
    PlotHelper.plot(dsigmoid_dx, plot_title=r"$\frac{d sigmoid(x)}{dx} = sigmoid(x)(1-sigmoid(x))$", y_coord_min=-1, y_coord_max=2)


def main():
    plot()


if __name__ == "__main__":
    main()