#!/usr/bin/env python
"""
Plot a 3-D function using matplotlib

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""
import numpy as np
from project.plothelper import PlotHelper


def plot():
    """Plot the function"""
    z = lambda x, y: x ** 2 + y ** 2  # define f(x)
    PlotHelper.plot(z, plot_title=r"$z = x^2 + y^2$", y_coord_min=-5, y_coord_max=5, dimensions=3)


def main():
    plot()


if __name__ == "__main__":
    main()
