#!/usr/bin/env python
"""
Plot y=e**(-x) using matplotlib

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""
import numpy as np
from project.plothelper import PlotHelper


def plot():
    """Plot the function"""
    f = lambda x: np.e ** (-x)  # define f(x)
    PlotHelper.plot(f, plot_title=r"$y=e^{-x}$")


def main():
    plot()


if __name__ == "__main__":
    main()
